server:
  host: "0.0.0.0"
  port: 3000
database:
  # IMPORTAN! This is used exclusively for dev deploy and should not be used in prod.
  # For production environments set the DATABASE_URL or OKTOSYNC_DB__URL environment variables instead.
  url: "postgres://user:secret@localhost:5432/oktosyncdb"
